FROM --platform=linux/amd64 gcr.io/distroless/static-debian11

ADD bin/etcd /usr/local/bin/
ADD bin/etcdctl /usr/local/bin/

WORKDIR /var/etcd/
WORKDIR /var/lib/etcd/

EXPOSE 2379 2380

# Define default command.
CMD ["/usr/local/bin/etcd"]
